[tox]
envlist = py39, py310, py311, py312, py313, flake8

[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 dq_db_manager tests

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    pytest
    pydantic
commands = pytest
